import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Suspense } from "react";
import Loading from "../loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProductLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex bg-red-200 flex-col gap-5 p-1">
          <Link
            className="bg-white w-[100px] text-center p-1 rounded"
            href={"/product/add"}
          >
            Product Add
          </Link>
          <Link
            className="bg-white w-[100px] text-center p-1 rounded"
            href={"/product/edit"}
          >
            Product Edit
          </Link>
        </div>
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
